#!/bin/bash
#./first 2>/dev/null
#./first 2>/dev/null | at now + 2 minute 2>/dev/null
#tail -f report
#add crontab thing, because I don't know how to get it working.
firstPID=0
./infinite &
string=`top | grep infinite`
echo $string
stringarray=($string)
firstPID=${stringarray[0]}
echo $firstPID
./infinite &
./infinite &

