#!/bin/bash
numberCheck='^[-,+]?[0-9]+$'
A=1
MODE="summing"
(tail -f pipe) |
while true; do
read LINE;
if [[ $LINE == "QUIT" ]]
then
echo "Scripts ended normally."
killall tail
exit
else
if [[ $LINE == "+" ]]
then
MODE="summing"
else
if [[ $LINE == "*" ]]
then
MODE="multiplying"
else
if ! [[ $LINE =~ $numberCheck ]]
then
echo $LINE "You should have inserted numbers. Scripts ended."
killall tail
exit
else
case $MODE in
summing)
let A=$A\+$LINE
;;
multiplying)
let A=$A\*$LINE
;;
esac
echo $A
fi
fi
fi
fi
done
